"""Final schema fix: Add screen_id column and promocode table

Revision ID: f23036dceecc
Revises: 
Create Date: 2025-12-01 15:37:26.284228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f23036dceecc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('seat_seatid', sa.String(length=50), nullable=False),
    sa.Column('seat_screen_id', sa.Integer(), nullable=False),
    sa.Column('reserved_by_user_id', sa.Integer(), nullable=True),
    # 💡 FIX: Added create_type=False
    sa.Column('status', sa.Enum('AVAILABLE', 'PENDING', 'BOOKED', name='seatstatus', create_type=False), nullable=False),
    sa.Column('hold_expiry_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reserved_by_user_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['screening_id'], ['screening.id'], ),
    sa.ForeignKeyConstraint(['seat_seatid', 'seat_screen_id'], ['seat.seatid', 'seat.screen_id'], name='fk_showseat_seat'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_id', 'seat_seatid', 'seat_screen_id', name='_show_seat_uc')
    )
    op.create_index(op.f('ix_show_seat_id'), 'show_seat', ['id'], unique=False)
    op.create_index(op.f('ix_show_seat_reserved_by_user_id'), 'show_seat', ['reserved_by_user_id'], unique=False)
    op.create_index(op.f('ix_show_seat_screening_id'), 'show_seat', ['screening_id'], unique=False)
    op.drop_table('seatlayout')
    op.drop_index(op.f('ix_booked_seat_id'), table_name='booked_seat')
    op.drop_table('booked_seat')
    op.drop_table('screeningdraft')
    op.drop_table('hall')
    op.drop_table('theaterowner')
    op.alter_column('User', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('User', 'role',
               existing_type=sa.VARCHAR(length=50),
               # 💡 FIX: Added create_type=False
               type_=sa.Enum('buyer', 'theatre_owner', 'super_admin', name='userrole', create_type=False),
               existing_nullable=False)
    op.drop_constraint(op.f('User_email_key'), 'User', type_='unique')
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.alter_column('booking', 'bookedat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('booking', 'status',
               existing_type=sa.VARCHAR(length=50),
               # 💡 FIX: Added create_type=False
               type_=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED', name='bookingstatus', create_type=False),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.create_index(op.f('ix_booking_bookingid'), 'booking', ['bookingid'], unique=False)
    op.add_column('bookingseat', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('bookingseat', sa.Column('booking_id', sa.Integer(), nullable=False))
    op.add_column('bookingseat', sa.Column('show_seat_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_bookingseat_id'), 'bookingseat', ['id'], unique=False)
    op.create_unique_constraint(None, 'bookingseat', ['show_seat_id'])
    op.drop_constraint(op.f('bookingseat_seatid_seatlayouthallid_seatlayoutcompanyid_se_fkey'), 'bookingseat', type_='foreignkey')
    op.drop_constraint(op.f('bookingseat_bookingid_fkey'), 'bookingseat', type_='foreignkey')
    op.create_foreign_key(None, 'bookingseat', 'booking', ['booking_id'], ['bookingid'])
    op.create_foreign_key(None, 'bookingseat', 'show_seat', ['show_seat_id'], ['id'])
    op.drop_column('bookingseat', 'seatid')
    op.drop_column('bookingseat', 'bookingid')
    op.drop_column('bookingseat', 'seatlayoutcompanyid')
    op.drop_column('bookingseat', 'seatlayoutbranchid')
    op.drop_column('bookingseat', 'seatlayouthallid')
    op.create_index(op.f('ix_promocode_code'), 'promocode', ['code'], unique=False)
    op.drop_constraint(op.f('promocode_createdbyadminid_fkey'), 'promocode', type_='foreignkey')
    op.drop_column('promocode', 'validfrom')
    op.drop_column('promocode', 'maxuses')
    op.drop_column('promocode', 'discountvalue')
    op.drop_column('promocode', 'scope')
    op.drop_column('promocode', 'applied_to')
    op.drop_column('promocode', 'discounttype')
    op.drop_column('promocode', 'createdbyadminid')
    op.drop_column('promocode', 'validto')
    op.drop_column('promocode', 'currentusecount')
    op.add_column('screening', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.add_column('screening', sa.Column('screen_id', sa.Integer(), nullable=False))
    op.add_column('screening', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('screening', sa.Column('price', sa.Float(), nullable=False))
    op.create_index(op.f('ix_screening_id'), 'screening', ['id'], unique=False)
    op.create_index(op.f('ix_screening_movie_id'), 'screening', ['movie_id'], unique=False)
    op.create_index(op.f('ix_screening_screen_id'), 'screening', ['screen_id'], unique=False)
    op.create_index(op.f('ix_screening_start_time'), 'screening', ['start_time'], unique=False)
    op.drop_constraint(op.f('screening_hallid_hallcompanyid_hallbranchid_fkey'), 'screening', type_='foreignkey')
    op.create_foreign_key(None, 'screening', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'screening', 'screen', ['screen_id'], ['id'])
    op.drop_column('screening', 'movieeidr')
    op.drop_column('screening', 'date')
    op.drop_column('screening', 'hallbranchid')
    op.drop_column('screening', 'hallcompanyid')
    op.drop_column('screening', 'starttime')
    op.drop_column('screening', 'status')
    op.drop_column('screening', 'hallid')
    op.add_column('seat', sa.Column('screen_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('seat_layouthallid_layoutcompanyid_layoutbranchid_fkey'), 'seat', type_='foreignkey')
    op.create_foreign_key(None, 'seat', 'screen', ['screen_id'], ['id'])
    op.drop_column('seat', 'layoutbranchid')
    op.drop_column('seat', 'layoutcompanyid')
    op.drop_column('seat', 'layouthallid')
    op.drop_constraint(op.f('theater_ownerid_fkey'), 'theater', type_='foreignkey')
    op.create_foreign_key(None, 'theater', 'theatreowner', ['ownerid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Downgrade logic typically involves dropping types that were created in upgrade.
    # Since this upgrade involves altering existing types, this section is complex and
    # best left untouched unless you absolutely need to reverse the migration.
    # The commands below are the original downgrade commands and should be fine.
    op.drop_constraint(None, 'theater', type_='foreignkey')
    op.create_foreign_key(op.f('theater_ownerid_fkey'), 'theater', 'theaterowner', ['ownerid'], ['id'])
    op.add_column('seat', sa.Column('layouthallid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('seat', sa.Column('layoutcompanyid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('seat', sa.Column('layoutbranchid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'seat', type_='foreignkey')
    op.create_foreign_key(op.f('seat_layouthallid_layoutcompanyid_layoutbranchid_fkey'), 'seat', 'seatlayout', ['layouthallid', 'layoutcompanyid', 'layoutbranchid'], ['layouthallid', 'layoutcompanyid', 'layoutbranchid'])
    op.drop_column('seat', 'screen_id')
    op.add_column('screening', sa.Column('hallid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('screening', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'SCHEDULED'::character varying"), autoincrement=False, nullable=False))
    op.add_column('screening', sa.Column('starttime', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('screening', sa.Column('hallcompanyid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('screening', sa.Column('hallbranchid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('screening', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('screening', sa.Column('movieeidr', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'screening', type_='foreignkey')
    op.drop_constraint(None, 'screening', type_='foreignkey')
    op.create_foreign_key(op.f('screening_hallid_hallcompanyid_hallbranchid_fkey'), 'screening', 'hall', ['hallid', 'hallcompanyid', 'hallbranchid'], ['hallid', 'companyid', 'branchid'])
    op.drop_index(op.f('ix_screening_start_time'), table_name='screening')
    op.drop_index(op.f('ix_screening_screen_id'), table_name='screening')
    op.drop_index(op.f('ix_screening_movie_id'), table_name='screening')
    op.drop_index(op.f('ix_screening_id'), table_name='screening')
    op.drop_column('screening', 'price')
    op.drop_column('screening', 'start_time')
    op.drop_column('screening', 'screen_id')
    op.drop_column('screening', 'movie_id')
    op.add_column('promocode', sa.Column('currentusecount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('promocode', sa.Column('validto', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('promocode', sa.Column('createdbyadminid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('promocode', sa.Column('discounttype', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('promocode', sa.Column('applied_to', sa.NUMERIC(precision=3, scale=2), server_default=sa.text('1.0'), autoincrement=False, nullable=False))
    op.add_column('promocode', sa.Column('scope', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('promocode', sa.Column('discountvalue', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('promocode', sa.Column('maxuses', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('promocode', sa.Column('validfrom', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('promocode_createdbyadminid_fkey'), 'promocode', 'superadmin', ['createdbyadminid'], ['id'])
    op.drop_index(op.f('ix_promocode_code'), table_name='promocode')
    op.add_column('bookingseat', sa.Column('seatlayouthallid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('bookingseat', sa.Column('seatlayoutbranchid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('bookingseat', sa.Column('seatlayoutcompanyid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('bookingseat', sa.Column('bookingid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bookingseat', sa.Column('seatid', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookingseat', type_='foreignkey')
    op.drop_constraint(None, 'bookingseat', type_='foreignkey')
    op.create_foreign_key(op.f('bookingseat_bookingid_fkey'), 'bookingseat', 'booking', ['bookingid'], ['bookingid'])
    op.create_foreign_key(op.f('bookingseat_seatid_seatlayouthallid_seatlayoutcompanyid_se_fkey'), 'bookingseat', 'seat', ['seatid', 'seatlayouthallid', 'seatlayoutcompanyid', 'seatlayoutbranchid'], ['seatid', 'layouthallid', 'layoutcompanyid', 'layoutbranchid'])
    op.drop_constraint(None, 'bookingseat', type_='unique')
    op.drop_index(op.f('ix_bookingseat_id'), table_name='bookingseat')
    op.drop_column('bookingseat', 'show_seat_id')
    op.drop_column('bookingseat', 'booking_id')
    op.drop_column('bookingseat', 'id')
    op.drop_index(op.f('ix_booking_bookingid'), table_name='booking')
    op.alter_column('booking', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED', name='bookingstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('booking', 'bookedat',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.create_unique_constraint(op.f('User_email_key'), 'User', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('User', 'role',
               existing_type=sa.Enum('buyer', 'theatre_owner', 'super_admin', name='userrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('User', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('theaterowner',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('businessname', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ownername', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('licensenumber', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bankdetails', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('logourl', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['User.id'], name='theaterowner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='theaterowner_pkey'),
    sa.UniqueConstraint('businessname', name='theaterowner_businessname_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('licensenumber', name='theaterowner_licensenumber_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('hall',
    sa.Column('hallid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('companyid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('branchid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['companyid', 'branchid'], ['theater.companyid', 'theater.branchid'], name='hall_companyid_branchid_fkey'),
    sa.PrimaryKeyConstraint('hallid', 'companyid', 'branchid', name='hall_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('screeningdraft',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('createdat', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('draftdata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ownerid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ownerid'], ['theaterowner.id'], name=op.f('screeningdraft_ownerid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('screeningdraft_pkey'))
    )
    op.create_table('booked_seat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_seat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.bookingid'], name=op.f('booked_seat_booking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booked_seat_pkey')),
    sa.UniqueConstraint('show_seat_id', name=op.f('booked_seat_show_seat_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_booked_seat_id'), 'booked_seat', ['id'], unique=False)
    op.create_table('seatlayout',
    sa.Column('layouthallid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('layoutcompanyid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('layoutbranchid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['layouthallid', 'layoutcompanyid', 'layoutbranchid'], ['hall.hallid', 'hall.companyid', 'hall.branchid'], name=op.f('seatlayout_layouthallid_layoutcompanyid_layoutbranchid_fkey')),
    sa.PrimaryKeyConstraint('layouthallid', 'layoutcompanyid', 'layoutbranchid', name=op.f('seatlayout_pkey'))
    )
    op.drop_index(op.f('ix_show_seat_screening_id'), table_name='show_seat')
    op.drop_index(op.f('ix_show_seat_reserved_by_user_id'), table_name='show_seat')
    op.drop_index(op.f('ix_show_seat_id'), table_name='show_seat')
    op.drop_table('show_seat')
    # ### end Alembic commands ###